### ISSUE TITLE
Visualizing Encounter histories post

### ISSUE THREAD

**Issue by Myfanwy** [fishsciences/DraftBlogPosts#1]
@hrbrmstr, 

The post is open for comments/edits!   First step will just be to make sure the data download links work.  Please read through and feel free to edit as you see fit, then push any changes and we'll get it up on the soon-to-launch CFS Blog (tentatively titled the Practical Pisces.).

**Comment by hrbrmstr** [comment]
I know you're hobnobbing with the R folks at rstudioconf but is `../../data/fishdata.csv` handy? I'd like to try to run the post as well as read it (if the data is share-able ;-)

**Comment by hrbrmstr** [comment]
ok, weird.

it wasn't downloading (GH was 404'ing it even after I had changed `eval=TRUE` and tried hand-downloading it) and now it is. this has been the story of my week #sigh

**Comment by Myfanwy** [comment]
haha no worries, glad it's working now!

**Comment by hrbrmstr** [comment]
Wow. I had totally forgotten how much fun that was (in what seems like "ages ago" time) and re-visiting it was a super cool boost for the end of a brutal week.

Totally minor edits/changes. It all worked and you explained things extremely well. They must miss you as a teaching assistant (both the professors and students). 

You are totally at liberty to revert any of my more nit-picky tweaks, too. 

And, the most surprising thing of all is that the fish font works on my really messed up macOS 10.13.4 beta 1 system (it's been "fun" the past week since the beta came out).

Hope the rest of the rstudioconf goes well!

**Comment by Myfanwy** [comment]
It's fun stuff, isn't it?  Thanks so much for taking the time, I'll send you an outline for the next few posts soon!  (you knew you were signing on for a 4-post contract, right? ;)
